In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [4]:
if torch.cuda.is_available():
  print("GpU is available")
  print(f"using gpu: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available so using cpu")

GpU is available
using gpu: Tesla T4


**Creating A Tensor**

In [6]:
a=torch.empty(2,3)

In [7]:
print(a)

tensor([[1.5209e-15, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [8]:
zeroT=torch.zeros(3,5)
print(zeroT)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
rnd=torch.rand(5,5)
print(rnd)

tensor([[0.8891, 0.2417, 0.3251, 0.5976, 0.2512],
        [0.1226, 0.2422, 0.5837, 0.5156, 0.7423],
        [0.4805, 0.2190, 0.7248, 0.1697, 0.4682],
        [0.1221, 0.9559, 0.5656, 0.9432, 0.5730],
        [0.2766, 0.0039, 0.0522, 0.5501, 0.3151]])


In [12]:
#use of seed
torch.manual_seed(100)
torch.rand(4,4)


tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

In [13]:
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

In [15]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
torch.arange(5,25)

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24])

In [17]:
torch.arange(1,100,3.5)

tensor([ 1.0000,  4.5000,  8.0000, 11.5000, 15.0000, 18.5000, 22.0000, 25.5000,
        29.0000, 32.5000, 36.0000, 39.5000, 43.0000, 46.5000, 50.0000, 53.5000,
        57.0000, 60.5000, 64.0000, 67.5000, 71.0000, 74.5000, 78.0000, 81.5000,
        85.0000, 88.5000, 92.0000, 95.5000, 99.0000])

In [18]:
torch.eye(10)# 10X10 identity Matrix

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])