**Tensor Shapes**

In [2]:
import torch

In [3]:
x=torch.tensor([[1,2,3],[5,6,9]])
print(x.shape)

torch.Size([2, 3])


In [5]:
torch.empty_like(x)# same shape as X

tensor([[    135776801128448, 8319683848551211643, 3180222411935070754],
        [8391722768137527840, 7959390389040738153, 2459013998934893172]])

In [7]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# **Tensor Data Types**

In [9]:
x.dtype

torch.int64

In [11]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [13]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.6815, 0.7155, 0.9436],
        [0.2038, 0.1971, 0.4445]], dtype=torch.float64)

# **Mathematical Operations**

## Scalar Operations

In [14]:
x

tensor([[1, 2, 3],
        [5, 6, 9]])

In [15]:
x+10

tensor([[11, 12, 13],
        [15, 16, 19]])

In [16]:
x**2

tensor([[ 1,  4,  9],
        [25, 36, 81]])

In [17]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.5000, 3.0000, 4.5000]])

In [18]:
x**x

tensor([[        1,         4,        27],
        [     3125,     46656, 387420489]])

In [19]:
x**x**x

tensor([[                   1,                   16,        7625597484987],
        [  361100275589084277,                    0, -2123029214124047543]])

# Element Wise **Operations**

In [20]:
a=torch.rand(5,7)
b=torch.rand(5,7)

In [22]:
a

tensor([[0.0577, 0.7618, 0.1221, 0.2608, 0.0378, 0.9912, 0.7607],
        [0.1213, 0.2218, 0.4671, 0.5974, 0.6371, 0.3738, 0.0077],
        [0.9765, 0.5774, 0.8755, 0.4014, 0.2258, 0.8708, 0.7140],
        [0.4618, 0.3774, 0.4147, 0.8344, 0.3798, 0.4457, 0.1382],
        [0.5983, 0.6479, 0.4976, 0.3000, 0.1894, 0.5503, 0.0247]])

In [23]:
a+b

tensor([[0.1603, 1.6091, 0.8721, 0.6760, 0.3904, 1.1402, 1.1255],
        [0.1489, 0.9247, 0.8884, 1.3490, 1.3506, 1.0624, 0.7519],
        [1.7956, 0.9006, 0.8853, 0.7611, 0.9235, 1.1934, 1.3287],
        [1.3813, 0.7928, 1.3705, 1.1047, 0.4478, 0.7793, 0.1606],
        [1.3972, 0.7103, 0.8615, 0.4396, 1.1173, 0.9455, 0.1798]])

In [24]:
a-b

tensor([[-0.0450, -0.0854, -0.6279, -0.1543, -0.3147,  0.8421,  0.3959],
        [ 0.0937, -0.4810,  0.0457, -0.1543, -0.0765, -0.3147, -0.7365],
        [ 0.1573,  0.2541,  0.8657,  0.0418, -0.4720,  0.5482,  0.0992],
        [-0.4577, -0.0381, -0.5412,  0.5641,  0.3117,  0.1121,  0.1158],
        [-0.2005,  0.5855,  0.1337,  0.1603, -0.7385,  0.1552, -0.1305]])

In [25]:
a*b

tensor([[0.0059, 0.6455, 0.0916, 0.1083, 0.0133, 0.1477, 0.2775],
        [0.0034, 0.1559, 0.1968, 0.4490, 0.4546, 0.2574, 0.0057],
        [0.7999, 0.1866, 0.0086, 0.1444, 0.1575, 0.2809, 0.4389],
        [0.4246, 0.1568, 0.3964, 0.2255, 0.0258, 0.1487, 0.0031],
        [0.4780, 0.0404, 0.1811, 0.0419, 0.1758, 0.2175, 0.0038]])

In [26]:
a/b

tensor([[5.6189e-01, 8.9918e-01, 1.6284e-01, 6.2825e-01, 1.0726e-01, 6.6504e+00,
         2.0854e+00],
        [4.3933e+00, 3.1563e-01, 1.1086e+00, 7.9478e-01, 8.9281e-01, 5.4290e-01,
         1.0333e-02],
        [1.1921e+00, 1.7861e+00, 8.9214e+01, 1.1161e+00, 3.2356e-01, 2.6994e+00,
         1.1614e+00],
        [5.0221e-01, 9.0833e-01, 4.3379e-01, 3.0870e+00, 5.5818e+00, 1.3362e+00,
         6.1652e+00],
        [7.4902e-01, 1.0387e+01, 1.3675e+00, 2.1485e+00, 2.0412e-01, 1.3928e+00,
         1.5903e-01]])

In [31]:
neg=torch.tensor([1,-23,-3.999,-4.33])

In [29]:
neg

tensor([ 1, -2, -3, -4])

In [32]:
torch.round(neg)

tensor([  1., -23.,  -4.,  -4.])

In [33]:
torch.ceil(neg)

tensor([  1., -23.,  -3.,  -4.])

In [35]:
torch.floor(neg)

tensor([  1., -23.,  -4.,  -5.])

reduction **operation**

In [39]:
a=torch.tensor([[1,3,6],[5,6,9]])

In [41]:
a

tensor([[1, 3, 6],
        [5, 6, 9]])

In [42]:
print(torch.sum(a))

tensor(30)


In [43]:
torch.sum(a,dim=0)

tensor([ 6,  9, 15])

In [44]:
torch.sum(a,dim=1)

tensor([10, 20])

In [49]:
b=torch.rand(5,3,dtype=torch.float64)

In [51]:
torch.mean(b,dim=0)

tensor([0.4669, 0.3580, 0.5969], dtype=torch.float64)

In [52]:
torch.mean(b,dim=1)

tensor([0.4926, 0.6339, 0.2896, 0.4636, 0.4901], dtype=torch.float64)

In [54]:
torch.median(b)

tensor(0.5784, dtype=torch.float64)

In [55]:
torch.max(b)

tensor(0.9366, dtype=torch.float64)

In [58]:
torch.min(b)

tensor(0.0402, dtype=torch.float64)

In [59]:
torch.prod(b)

tensor(7.7051e-08, dtype=torch.float64)

In [60]:
torch.var(b)

tensor(0.0880, dtype=torch.float64)

In [61]:
torch.argmax(b)

tensor(12)

In [64]:
m=torch.rand(5,5)

In [65]:
torch.matmul(m,m)

tensor([[1.2890, 1.5815, 1.4575, 2.0687, 1.2786],
        [1.6344, 2.1988, 2.0058, 2.6517, 1.7127],
        [1.2432, 2.1377, 1.9716, 2.4364, 1.5378],
        [0.9268, 1.6916, 1.3158, 2.0933, 1.1030],
        [1.2879, 2.0183, 1.2348, 2.6323, 1.4847]])

In [67]:
torch.transpose(m,0,1)

tensor([[0.0182, 0.1478, 0.3170, 0.6179, 0.9945],
        [0.8569, 0.8216, 0.7843, 0.4498, 0.4656],
        [0.2706, 0.9028, 0.9242, 0.3972, 0.1314],
        [0.9086, 0.7225, 0.6786, 0.8866, 0.8577],
        [0.5176, 0.7820, 0.4115, 0.1764, 0.6328]])

In [68]:
torch.det(m)

tensor(0.0736)

In [70]:
torch.inverse(m)

tensor([[-0.4063, -1.4934,  1.8222, -0.9884,  1.2683],
        [ 1.8487, -3.7808,  4.4351, -3.3890,  1.2203],
        [-1.2180,  1.3057, -0.1994,  1.1068, -0.7960],
        [-0.0217,  1.9276, -3.0402,  3.1232, -1.2577],
        [-0.4394,  2.2452, -1.9652, -0.4158,  0.5591]])

In [72]:
m1=torch.rand(3,3)
m2=torch.rand(3,3)

In [73]:
m1==m2

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [74]:
m1>m2

tensor([[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [75]:
m1<m2

tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])

In [76]:
m1!=m2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# Special **fn**

In [78]:
torch.exp(m1)

tensor([[1.0453, 1.4022, 2.5443],
        [1.9748, 1.8058, 2.3798],
        [2.5786, 1.4380, 2.2681]])

In [79]:
torch.sqrt(m1)

tensor([[0.2106, 0.5814, 0.9664],
        [0.8249, 0.7688, 0.9311],
        [0.9733, 0.6027, 0.9050]])

In [80]:
torch.sigmoid(m1)

tensor([[0.5111, 0.5837, 0.7179],
        [0.6638, 0.6436, 0.7041],
        [0.7206, 0.5898, 0.6940]])

In [81]:
torch.tanh(m1)

tensor([[0.0443, 0.3257, 0.7324],
        [0.5918, 0.5306, 0.6999],
        [0.7385, 0.3481, 0.6745]])

In [82]:
torch.relu(m1)

tensor([[0.0443, 0.3380, 0.9338],
        [0.6805, 0.5910, 0.8670],
        [0.9472, 0.3632, 0.8190]])

In [84]:
nm=torch.rand(size=(5,5),dtype=torch.float64)

In [85]:
torch.softmax(nm,dim=0)

tensor([[0.1287, 0.1390, 0.2475, 0.2568, 0.1726],
        [0.2112, 0.1790, 0.1647, 0.2230, 0.1559],
        [0.1687, 0.2337, 0.2572, 0.2314, 0.2045],
        [0.2616, 0.1540, 0.2199, 0.1024, 0.2801],
        [0.2298, 0.2942, 0.1106, 0.1864, 0.1869]], dtype=torch.float64)

# **Inplace Operation**

In [86]:
m

tensor([[0.0182, 0.8569, 0.2706, 0.9086, 0.5176],
        [0.1478, 0.8216, 0.9028, 0.7225, 0.7820],
        [0.3170, 0.7843, 0.9242, 0.6786, 0.4115],
        [0.6179, 0.4498, 0.3972, 0.8866, 0.1764],
        [0.9945, 0.4656, 0.1314, 0.8577, 0.6328]])

In [87]:
m1

tensor([[0.0443, 0.3380, 0.9338],
        [0.6805, 0.5910, 0.8670],
        [0.9472, 0.3632, 0.8190]])

In [88]:
m2

tensor([[0.7742, 0.2138, 0.8388],
        [0.1117, 0.0598, 0.0569],
        [0.7727, 0.2460, 0.6358]])

In [89]:
m1.add_(m2)

tensor([[0.8185, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [90]:
m1

tensor([[0.8185, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [91]:
torch.relu_(m1)

tensor([[0.8185, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

# Copying A **tensor**

In [92]:
m1

tensor([[0.8185, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [93]:
mm=m1

In [94]:
mm[0][0]=0

In [95]:
m1

tensor([[0.0000, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [96]:
mm

tensor([[0.0000, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [97]:
print(id(m1)==id(mm))

True


In [98]:
mmm=m1.clone()

In [99]:
print(id(mmm)==id(m1))

False


# **Tensor Operations On GPU**

In [100]:
torch.cuda.is_available()

True

In [101]:
device=torch.device('cuda')

In [102]:
torch.rand((5,5),device=device)

tensor([[0.6016, 0.9772, 0.9172, 0.3152, 0.4041],
        [0.3134, 0.9153, 0.3571, 0.3666, 0.4474],
        [0.3439, 0.6586, 0.0469, 0.8055, 0.5312],
        [0.4294, 0.7170, 0.8839, 0.7082, 0.3492],
        [0.6882, 0.2077, 0.2202, 0.6823, 0.9656]], device='cuda:0')

In [103]:
m1

tensor([[0.0000, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]])

In [104]:
gp=m1.to(device)

In [105]:
gp

tensor([[0.0000, 0.5518, 1.7726],
        [0.7922, 0.6508, 0.9239],
        [1.7199, 0.6092, 1.4547]], device='cuda:0')

Reshaping ***Tensors***

In [2]:
import torch

In [3]:
a=torch.rand(5,3,3)

In [4]:
a.flatten()

tensor([0.7842, 0.8037, 0.7174, 0.9190, 0.4511, 0.7607, 0.6449, 0.1445, 0.9590,
        0.5437, 0.2011, 0.9102, 0.6092, 0.8078, 0.4207, 0.4474, 0.0585, 0.2401,
        0.8237, 0.0670, 0.2066, 0.6230, 0.4405, 0.4888, 0.8759, 0.7424, 0.7981,
        0.7567, 0.2911, 0.8578, 0.0157, 0.3235, 0.3357, 0.2545, 0.2317, 0.8898,
        0.7689, 0.2999, 0.3891, 0.4411, 0.6116, 0.8475, 0.6739, 0.7107, 0.8363])

In [5]:
b=torch.rand(5,5,5,5,5,5)

In [6]:
b.flatten()

tensor([0.3068, 0.6134, 0.3733,  ..., 0.2467, 0.5234, 0.8380])

In [7]:
c=torch.rand(226,226,3)

In [11]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [12]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [13]:
c.squeeze(0).shape

torch.Size([226, 226, 3])

# NUmPy And **PyTorch**

In [14]:
import numpy as np

In [17]:
m=torch.rand(4,3)

In [18]:
mm=m.numpy()

In [19]:
mm

array([[0.34807426, 0.28008997, 0.808199  ],
       [0.9869765 , 0.24107003, 0.6688592 ],
       [0.6636093 , 0.61734027, 0.47603643],
       [0.71903616, 0.5406279 , 0.13148278]], dtype=float32)

In [20]:
torch.from_numpy(mm)

tensor([[0.3481, 0.2801, 0.8082],
        [0.9870, 0.2411, 0.6689],
        [0.6636, 0.6173, 0.4760],
        [0.7190, 0.5406, 0.1315]])