In [1]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 74.8 MB/s eta 0:00:00


# **Import Trained Model**

In [2]:
import gensim.downloader as api
model=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


# **Example Of Word As Vector**

In [3]:
word_vectors=model

In [5]:
print(word_vectors['zebra'])

[-0.08544922 -0.10253906 -0.48632812  0.23828125  0.02502441 -0.10595703
  0.15332031 -0.11816406 -0.26367188 -0.06933594  0.23925781 -0.05810547
 -0.14550781 -0.3359375  -0.5        -0.26757812 -0.39453125  0.16503906
 -0.29296875 -0.19238281 -0.00094986  0.10693359  0.14257812  0.01104736
 -0.02246094  0.08300781 -0.26367188  0.34570312  0.47460938 -0.33398438
 -0.09375     0.06396484  0.12060547 -0.21582031 -0.12158203  0.19433594
  0.24511719  0.16308594 -0.06787109  0.21289062 -0.03564453 -0.07226562
  0.24804688  0.20800781 -0.13183594 -0.22460938 -0.06933594 -0.01623535
  0.17285156  0.29296875 -0.21972656 -0.19726562  0.17773438 -0.17382812
  0.08544922  0.19726562  0.05371094 -0.11816406 -0.03710938  0.3125
  0.05126953 -0.01904297  0.16308594 -0.38476562  0.125      -0.07958984
  0.01049805 -0.09619141 -0.06201172 -0.05249023  0.51953125  0.05541992
 -0.23046875  0.11621094 -0.3359375   0.24414062  0.2890625  -0.23242188
 -0.27929688  0.13769531 -0.17480469 -0.32226562  0.057

In [9]:
print(word_vectors.most_similar(positive=['King','Woman'],negative=['Man'],topn=10))

[('Queen', 0.4929387867450714), ('Tupou_V.', 0.45174285769462585), ('Oprah_BFF_Gayle', 0.4422132968902588), ('Jackson', 0.440250426530838), ('NECN_Alison', 0.4331282675266266), ('Whitfield', 0.42834725975990295), ('Ida_Vandross', 0.42084527015686035), ('prosecutor_Dan_Satterberg', 0.420758992433548), ('martin_Luther_King', 0.42059651017189026), ('Coretta_King', 0.4202733635902405)]


In [6]:
print(word_vectors['vector'].shape)

(300,)


# SimilaritY Between A Pair Of **Words**

In [16]:
print(word_vectors.similarity('Husband','Wife'))
print(word_vectors.similarity('Father','Son'))
print(word_vectors.similarity('Cat','Kitten'))
print(word_vectors.similarity('Rich','Money'))
print(word_vectors.similarity('Brother','Sister'))
print(word_vectors.similarity('Knowledge','Job'))
print(word_vectors.similarity('Job','Money'))
print(word_vectors.similarity('Intelligence','Money'))
print(word_vectors.similarity('Uncle','Aunt'))

0.6944963
0.4729275
0.5458111
0.1763649
0.46230957
0.2437579
0.29577595
0.13679546
0.49551338


In [17]:
print(word_vectors.most_similar('Money',topn=3))

[('money', 0.5733489990234375), ('Stuart_Fagg_ninemsn', 0.5603213310241699), ('Desperate_Housewives_Dirty_Sexy', 0.5515798330307007)]


# **Create Token Embeddings**

In [1]:
import torch

In [2]:
input_ids=torch.tensor([2,3,5,1])

In [3]:
vocab_size=6
output_dim=3

In [6]:
torch.manual_seed(123)
embedding_layer=torch.nn.Embedding(vocab_size,output_dim)

In [7]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [8]:
print(embedding_layer.weight[3])

tensor([-0.4015,  0.9666, -1.1481], grad_fn=<SelectBackward0>)


In [9]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [10]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
